language: php
php:
  - 5.5
  - 5.6
  - 7.0 
  - 7.1 
branches:
  only:
    - master
before_install:
  - travis_retry composer self-update
  - composer install
script:
  - composer test
  - vendor/bin/phpcs --standard=PSR2 mik tests src
# after_success:
#  - bash <(curl -s https://codecov.io/bash)
