language: php
php:
  - 5.5
  - 5.6
  - 7.0 
branches:
  only:
    master
before_install:
  - travis_retry composer self-update
  - composer install
script:
  - phpunit --exclude-group inputvalidators --bootstrap vendor/autoload.php tests
  - phpunit --group inputvalidators --bootstrap vendor/autoload.php tests
