language: php
php:
  - 5.5
  - 5.6
branches:
  only:
    issue-272
before_install:
  - travis_retry composer self-update
  - composer install
script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests
