language: php
php:
  - 5.5
  - 5.6
  - 7.0 
branches:
  only:
    - master
before_install:
  - travis_retry composer self-update
  - composer install
script:
  - composer test
after_success:
  - bash <(curl -s https://codecov.io/bash)
