<?php
// src/metadatamanipulators/SimpleReplaceOai.php

namespace mik\metadatamanipulators;

use \Monolog\Logger;

/**
 * SimpleReplaceOai- Allows the application of preg_replace() to XML
 * documents generated by the Oai MODS and OAI DC metadata parsers.
 * This manipulator does not manipulate the DOM, it applies a regex
 * to the input XML as a string.
 *
 * Signature in .ini files is:
 *
 *   metadatamanipulators[] = "SimpleReplaceOai|/pattern/|replacement text"
 * e.g.,
 *   metadatamanipulators[] = "SimpleReplaceOai|/<title>Page/|<title>Part"
 *
 * Note that the pattern must contain the /s or /m modifier as needed.
 */
class SimpleReplaceOai extends MetadataManipulator
{
    /**
     * Create a new metadata manipulator instance.
     */
    public function __construct($settings, $paramsArray, $record_key)
    {
        parent::__construct($settings, $paramsArray, $record_key);
        $this->record_key = $record_key;

        // Set up logger.
        $this->pathToLog = $this->settings['LOGGING']['path_to_manipulator_log'];
        $this->log = new \Monolog\Logger('config');
        $this->logStreamHandler = new \Monolog\Handler\StreamHandler(
            $this->pathToLog,
            Logger::INFO
        );
        $this->log->pushHandler($this->logStreamHandler);

        if (count($paramsArray) == 2) {
            // A PHP preg_ pattern to match the original value on.
            $this->replacePattern = $paramsArray[0];
            // A replacement string.
            $this->replacementText = $paramsArray[1];
        } elseif (count($paramsArray) == 1) {
            // A PHP preg_ pattern to match the original value on.
            $this->replacePattern = $paramsArray[0];
            // Empty replacement.
            $this->replacementText = '';
        } else {
            $this->log->addInfo("SimpleReplaceOai", array('Wrong parameter count' => count($paramsArray)));
        }
    }

    /**
     * General manipulate wrapper method.
     *
     * @param string $input An XML file to be manipulated.
     *
     * @return string
     *     Manipulated string
     */
    public function manipulate($input)
    {
        if (preg_match($this->replacePattern, $input)) {
            $modified_input = preg_replace($this->replacePattern, $this->replacementText, $input);
            $this->log->addInfo("SimpleReplaceOai", array('Record key' => $this->record_key,
                'Input' => $input,
                'Modified version' => $modified_input
                ));
            return $modified_input;
        } else {
            // If current XML file does not match our regex, return it.
            return $input;
        }
    }
}
